# Generated by Django 4.2.1 on 2023-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
                ('disciplina', models.CharField(default='', max_length=100)),
                ('etcs', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('✅', 'APROVADO'), ('🛑', 'REPROVADO'), ('EM CURSO', 'EM CURSO')], default='EM CURSO', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField(choices=[('GAMING', 'GAMING'), ('LIVROS', 'LIVROS'), ('AUDIO', 'AUDIO'), ('TV', 'TV'), ('ANIME', 'ANIME')], default='ANIME', max_length=15)),
                ('descricao', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=75)),
                ('descricao', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
