# Generated by Django 4.2.1 on 2023-06-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
                ('disciplina', models.CharField(default='', max_length=100)),
                ('etcs', models.IntegerField(default=0)),
                ('estado', models.CharField(default='Em curso', max_length=25)),
            ],
        ),
    ]
