# Generated by Django 4.2.1 on 2023-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='estado',
            field=models.IntegerField(choices=[(1, 'APROVADO'), (2, 'REPROVADO'), (3, 'EM CURSO')], default=3),
        ),
    ]
