# Generated by Django 4.2.1 on 2023-06-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_cadeira_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='estado',
            field=models.IntegerField(choices=[('✅', 'APROVADO'), ('🛑', 'REPROVADO'), ('EM CURSO', 'EM CURSO')], default='EM CURSO'),
        ),
    ]
