# Generated by Django 4.2.1 on 2023-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_cadeira_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='dataInicio',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='tipo',
            field=models.CharField(choices=[('ACADEMICO', 'ACADEMICO'), ('PROFISSIONAL', 'PROFISSIONAL'), ('CERTIFICACAO', 'CERTIFICACAO'), ('SKILLS', 'SKILLS')], default='ACADEMICO', max_length=15),
        ),
    ]
