# Generated by Django 4.2.1 on 2023-06-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_cadeira_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField(choices=[('GAMING', 'GAMING'), ('LIVROS', 'LIVROS'), ('MÚSICA', 'MÚSICA'), ('SERIES/FILMES', 'SERIES/FILMES'), ('SERIES/FILMES', 'SERIES/FILMES')], default='GAMING', max_length=15)),
                ('descricao', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
