# Generated by Django 4.2.1 on 2023-06-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='categoria',
            field=models.TextField(choices=[('GAMING', 'GAMING'), ('LIVROS', 'LIVROS'), ('AUDIO', 'AUDIO'), ('TV', 'TV'), ('ANIME', 'ANIME')], default='ANIME', max_length=15),
        ),
    ]
