# Generated by Django 4.2.1 on 2023-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_backend_descricao_alter_frontend_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='dataFim',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='dataInicio',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
