# Generated by Django 4.2.1 on 2023-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_skill_alter_curriculo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
