# Generated by Django 4.2.1 on 2023-06-14 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_curriculo_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor tem de ser no mínimo 1'), django.core.validators.MaxValueValidator(5, message='O valor tem de ser no máximo 5')]),
        ),
    ]
