# Generated by Django 4.2.1 on 2023-06-14 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_cadeira_ano_alter_cadeira_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ano',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='O valor tem de ser no mínimo 1'), django.core.validators.MaxValueValidator(3, message='O valor tem de ser no máximo 3')]),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='etcs',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1, message='O valor tem de ser no mínimo 1'), django.core.validators.MaxValueValidator(7, message='O valor tem de ser no máximo 7')]),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='semestre',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='O valor tem de ser no mínimo 1'), django.core.validators.MaxValueValidator(2, message='O valor tem de ser no máximo 2')]),
        ),
    ]
