# Generated by Django 4.2.1 on 2023-06-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_cadeira_ano_alter_cadeira_etcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ano',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='estado',
            field=models.CharField(choices=[('✅', 'APROVADO'), ('🛑', 'REPROVADO'), ('DECORRER', 'EM CURSO')], default='DECORRER', max_length=25),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='etcs',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
